const post = [
  {
    id: 1,
    title: "Kenapa kamu benci padaku?",
    content: "Content 1",
    author: "Author 1",
    image: "https://via.placeholder.com/150",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    category: "Category 1",
    tags: ["Tag 1", "Tag 2"],
    comments: [
      {
        id: 1,
        content: "Comment 1",
        author: "Author 1 Gilang Dirga",
        createdAt: "2021-01-01",
        updatedAt: "2021-01-01",
      },
    ],
    views: 0,
  },
  {
    id: 2,
    title: "Enak nih ini",
    content: "Content 2",
    author: "Author 2",
    image: "https://via.placeholder.com/150",
    createdAt: "2021-01-02",
    updatedAt: "2021-01-02",
    category: "Category 2",
    tags: ["Tag 3", "Tag 4"],
    comments: [
      {
        id: 1,
        content: "Serius beneran enak nih ?",
        author: "Author 1 Gilang Dirga",
        createdAt: "2021-01-01",
        updatedAt: "2021-01-01",
      },
    ],
    views: 0,
  },
  {
    id: 3,
    title: "Enak nih ini",
    content: "Content 3",
    author: "Author 3",
    image: "https://via.placeholder.com/150",
    createdAt: "2021-01-03",
    updatedAt: "2021-01-03",
    category: "Category 3",
    tags: ["Tag 5", "Tag 6"],
    comments: [
      {
        id: 1,
        content: "Serius beneran enak nih ?",
        author: "Author 1 Gilang Dirga",
        createdAt: "2021-01-01",
        updatedAt: "2021-01-01",
      },
    ],
    views: 0,
  },
  {
    id: 4,
    title: "Enak nih ini",
    content: "Content 4",
    author: "Author 4",
    image: "https://via.placeholder.com/150",
    createdAt: "2021-01-04",
    updatedAt: "2021-01-04",
    category: "Category 4",
    tags: ["Tag 7", "Tag 8"],
    comments: [
      {
        id: 1,
        content: "Serius beneran enak nih ?",
        author: "Author 1 Gilang Dirga",
        createdAt: "2021-01-01",
        updatedAt: "2021-01-01",
      },
    ],
    views: 0,
  },
  {
    id: 5,
    title: "Enak nih ini",
    content: "Content 5",
    author: "Author 5",
    image: "https://via.placeholder.com/150",
    createdAt: "2021-01-05",
    updatedAt: "2021-01-05",
    category: "Category 5",
    tags: ["Tag 9", "Tag 10"],
    comments: [
      {
        id: 1,
        content: "Serius beneran enak nih ?",
        author: "Author 1 Gilang Dirga",
        createdAt: "2021-01-01",
        updatedAt: "2021-01-01",
      },
    ],
    views: 0,
  },
  {
    id: 6,
    title: "Enak nih ini",
    content: "Content 6",
    author: "Author 6",
    image: "https://via.placeholder.com/150",
    createdAt: "2021-01-06",
    updatedAt: "2021-01-06",
    category: "Category 6",
    tags: ["Tag 11", "Tag 12"],
    comments: [
      {
        id: 1,
        content: "Serius beneran enak nih ?",
        author: "Author 1 Gilang Dirga",
        createdAt: "2021-01-01",
        updatedAt: "2021-01-01",
      },
    ],
    views: 0,
  },
];

export default post;
